language: ruby
bundler_args: --without development
script: "bundle exec rspec --color --format documentation spec"
rvm:
  - "2.1"
  - "2.0"
  - "1.9.3"
  - "jruby-19mode"
  - "1.9.2"
  - "rbx-2"
  - "1.8.7"
notifications:
  email: matt@soupmatt.com
services:
  - rabbitmq
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: 1.8.7
